name: tag

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: golang:1.14-alpine3.11
    steps:
      - name: Prepare
        run: apk -U upgrade && apk add build-base git ca-certificates sqlite

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          make build-deps deps test deploy
          ls -1 bin/ | xargs -I{} tar vzc -f `pwd`/bin/{}.tgz -C `pwd`/bin/{} .

      - name: Upload Release Assets
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/*.tgz
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
